package registry

type OptimulaConceptConst int32

const CONCEPT_TIMESHEETS_PLAN = OptimulaConceptConst(1001)
const CONCEPT_TIMESHEETS_WORK = OptimulaConceptConst(1002)
const CONCEPT_TIMEACTUAL_WORK = OptimulaConceptConst(1003)
const CONCEPT_PAYMENT_BASIS   = OptimulaConceptConst(2001)
const CONCEPT_PAYMENT_HOURS   = OptimulaConceptConst(2002)
const CONCEPT_PAYMENT_FIXED   = OptimulaConceptConst(2003)
const CONCEPT_OPTIMUS_BASIS   = OptimulaConceptConst(2011)
const CONCEPT_OPTIMUS_HOURS   = OptimulaConceptConst(2012)
const CONCEPT_OPTIMUS_FIXED   = OptimulaConceptConst(2013)
const CONCEPT_OPTIMUS_NETTO   = OptimulaConceptConst(2014)
const CONCEPT_REDUCED_BASIS   = OptimulaConceptConst(2021)
const CONCEPT_REDUCED_HOURS   = OptimulaConceptConst(2022)
const CONCEPT_REDUCED_FIXED   = OptimulaConceptConst(2023)
const CONCEPT_REDUCED_NETTO   = OptimulaConceptConst(2024)
const CONCEPT_AGRWORK_HOURS   = OptimulaConceptConst(2031)
const CONCEPT_AGRTASK_HOURS   = OptimulaConceptConst(2032)
const CONCEPT_ALLOWCE_MFULL   = OptimulaConceptConst(3001)
const CONCEPT_ALLOWCE_HFULL   = OptimulaConceptConst(3002)
const CONCEPT_ALLOWCE_HOURS   = OptimulaConceptConst(3003)
const CONCEPT_ALLOWCE_DAILY   = OptimulaConceptConst(3004)
const CONCEPT_ALLDOWN_DAILY   = OptimulaConceptConst(3005)
const CONCEPT_OFFWORK_HOURS   = OptimulaConceptConst(3011)
const CONCEPT_OFFTASK_HOURS   = OptimulaConceptConst(3012)
const CONCEPT_OFFSETS_HFULL   = OptimulaConceptConst(3013)
const CONCEPT_OFFSETS_HOURS   = OptimulaConceptConst(3014)
const CONCEPT_OFFSETS_DAILY   = OptimulaConceptConst(3015)
const CONCEPT_OFFDOWN_DAILY   = OptimulaConceptConst(3016)
const CONCEPT_SETTLEM_TARGETS = OptimulaConceptConst(4001)
const CONCEPT_SETTLEM_TARNETT = OptimulaConceptConst(4002)
const CONCEPT_SETTLEM_AGRWORK = OptimulaConceptConst(4003)
const CONCEPT_SETTLEM_AGRTASK = OptimulaConceptConst(4004)
const CONCEPT_SETTLEM_ALLOWCE = OptimulaConceptConst(4005)
const CONCEPT_SETTLEM_ALLNETT = OptimulaConceptConst(4006)
const CONCEPT_SETTLEM_OFFWORK = OptimulaConceptConst(4011)
const CONCEPT_SETTLEM_OFFTASK = OptimulaConceptConst(4012)
const CONCEPT_SETTLEM_OFFSETS = OptimulaConceptConst(4013)
const CONCEPT_SETTLEM_RESULTS = OptimulaConceptConst(4014)
const CONCEPT_SETTLEM_RESNETT = OptimulaConceptConst(4015)
const CONCEPT_INCOMES_TAXFREE = OptimulaConceptConst(5001)
const CONCEPT_INCOMES_TAXBASE = OptimulaConceptConst(5002)
const CONCEPT_INCOMES_TAXWINS = OptimulaConceptConst(5003)
const CONCEPT_INCOMES_SUMMARY = OptimulaConceptConst(5004)

func (tcc OptimulaConceptConst) Id() int32 {
	return int32(tcc)
}

func (tcc OptimulaConceptConst) String() string {
	switch tcc {
	case CONCEPT_TIMESHEETS_PLAN: return "CONCEPT_TIMESHEETS_PLAN"
	case CONCEPT_TIMESHEETS_WORK: return "CONCEPT_TIMESHEETS_WORK"
	case CONCEPT_TIMEACTUAL_WORK: return "CONCEPT_TIMEACTUAL_WORK"
	case CONCEPT_PAYMENT_BASIS  : return "CONCEPT_PAYMENT_BASIS"
	case CONCEPT_PAYMENT_HOURS  : return "CONCEPT_PAYMENT_HOURS"
	case CONCEPT_PAYMENT_FIXED  : return "CONCEPT_PAYMENT_FIXED"
	case CONCEPT_OPTIMUS_BASIS  : return "CONCEPT_OPTIMUS_BASIS"
	case CONCEPT_OPTIMUS_HOURS  : return "CONCEPT_OPTIMUS_HOURS"
	case CONCEPT_OPTIMUS_FIXED  : return "CONCEPT_OPTIMUS_FIXED"
	case CONCEPT_OPTIMUS_NETTO  : return "CONCEPT_OPTIMUS_NETTO"
	case CONCEPT_REDUCED_BASIS  : return "CONCEPT_REDUCED_BASIS"
	case CONCEPT_REDUCED_HOURS  : return "CONCEPT_REDUCED_HOURS"
	case CONCEPT_REDUCED_FIXED  : return "CONCEPT_REDUCED_FIXED"
	case CONCEPT_REDUCED_NETTO  : return "CONCEPT_REDUCED_NETTO"
	case CONCEPT_AGRWORK_HOURS  : return "CONCEPT_AGRWORK_HOURS"
	case CONCEPT_AGRTASK_HOURS  : return "CONCEPT_AGRTASK_HOURS"
	case CONCEPT_ALLOWCE_MFULL  : return "CONCEPT_ALLOWCE_MFULL"
	case CONCEPT_ALLOWCE_HFULL  : return "CONCEPT_ALLOWCE_HFULL"
	case CONCEPT_ALLOWCE_HOURS  : return "CONCEPT_ALLOWCE_HOURS"
	case CONCEPT_ALLOWCE_DAILY  : return "CONCEPT_ALLOWCE_DAILY"
	case CONCEPT_ALLDOWN_DAILY  : return "CONCEPT_ALLDOWN_DAILY"
	case CONCEPT_OFFWORK_HOURS  : return "CONCEPT_OFFWORK_HOURS"
	case CONCEPT_OFFTASK_HOURS  : return "CONCEPT_OFFTASK_HOURS"
	case CONCEPT_OFFSETS_HFULL  : return "CONCEPT_OFFSETS_HFULL"
	case CONCEPT_OFFSETS_HOURS  : return "CONCEPT_OFFSETS_HOURS"
	case CONCEPT_OFFSETS_DAILY  : return "CONCEPT_OFFSETS_DAILY"
	case CONCEPT_OFFDOWN_DAILY  : return "CONCEPT_OFFDOWN_DAILY"
	case CONCEPT_SETTLEM_TARGETS: return "CONCEPT_SETTLEM_TARGETS"
	case CONCEPT_SETTLEM_TARNETT: return "CONCEPT_SETTLEM_TARNETT"
	case CONCEPT_SETTLEM_AGRWORK: return "CONCEPT_SETTLEM_AGRWORK"
	case CONCEPT_SETTLEM_AGRTASK: return "CONCEPT_SETTLEM_AGRTASK"
	case CONCEPT_SETTLEM_ALLOWCE: return "CONCEPT_SETTLEM_ALLOWCE"
	case CONCEPT_SETTLEM_ALLNETT: return "CONCEPT_SETTLEM_ALLNETT"
	case CONCEPT_SETTLEM_OFFWORK: return "CONCEPT_SETTLEM_OFFWORK"
	case CONCEPT_SETTLEM_OFFTASK: return "CONCEPT_SETTLEM_OFFTASK"
	case CONCEPT_SETTLEM_OFFSETS: return "CONCEPT_SETTLEM_OFFSETS"
	case CONCEPT_SETTLEM_RESULTS: return "CONCEPT_SETTLEM_RESULTS"
	case CONCEPT_SETTLEM_RESNETT: return "CONCEPT_SETTLEM_RESNETT"
	case CONCEPT_INCOMES_TAXFREE: return "CONCEPT_INCOMES_TAXFREE"
	case CONCEPT_INCOMES_TAXBASE: return "CONCEPT_INCOMES_TAXBASE"
	case CONCEPT_INCOMES_TAXWINS: return "CONCEPT_INCOMES_TAXWINS"
	case CONCEPT_INCOMES_SUMMARY: return "CONCEPT_INCOMES_SUMMARY"
	}
	return "CONCEPT_UNKNOWN"
}

